import turtle
h = turtle.Turtle()
h.shape("turtle")
w = turtle.Screen()
w.bgcolor("black")
h.color("red")
h.begin_fill()
h.fillcolor("red")
h.left(140)
h.fd(150)
h.circle(-100,200)
h.left(120)
h.circle(-100,200)
h.forward(204)
h.right(90)
h.forward(50)
h.end_fill()
h.hideturtle()
